name: Deploy FastAPI Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: Sithi5/remote-ssh-commands-action@1.1.2
        with:
          SSH_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_REMOTE_COMMANDS: | 
            echo "Prueba."
